import type { LearnLesson } from './learn-content';

// Keep the existing module slug so saved course links continue to work.
const base = { module: 'Replit 101', duration: '4 min', video: '', replitExample: '' };

export const discoverLessons: LearnLesson[] = [
  {
    ...base, title: 'What You Can Do with Replit',
    summary: 'Welcome! Whether you’re new to Replit or have built a few projects with it, this is a place to discover what you can do. Replit helps you explore information, get work done, and turn your ideas into apps.',
    introduction: [
      { text: 'For example, you can:', items: ['Research an idea, compare options, and check sources.', 'Summarize notes or find information in tools you choose to connect.', 'Schedule recurring tasks, such as a weekly update.', 'Turn an idea into a web app you can try and improve.', 'Explore different designs and create visual assets, such as images.'] },
      'The good news is that you don’t need technical or coding experience to get started. You describe what you want, review the result, and ask Replit for improvements.',
      { text: 'Before you begin, have these ready:', items: ['A Replit account you can sign into.', 'A Google account with Google Calendar that you’re allowed to connect to Replit. A personal or test account works well; a managed work or school account may need administrator approval.', 'Fictional party details for practice. Don’t include a child’s name, photo, or home address.'] },
      'We’ll connect Google Calendar in “Connect your tools.” You don’t need to connect it before starting. Gmail is not required for this exercise, and you can read along without connecting an account.',
      { text: 'Throughout this course, you’ll plan a child’s birthday party. Step by step, you’ll:', items: ['Brainstorm ideas and explore party themes.', 'Connect Google Calendar, then ask Replit to add the birthday event.', 'Create a shopping list of things to buy.', 'Build a website where guests can RSVP.', 'Design invitations and create supporting images.'] },
      'You can use fictional details while practicing. Let’s get started!',
    ],
    sections: [],
    quiz: [
      { prompt: 'Which of these can you do with Replit? Choose the answer that includes every possibility.', choices: ['Explore information and research ideas', 'Get work done with information from connected tools', 'Create Routines for recurring tasks', 'Build applications', 'Explore designs and create images', 'All of the above'], answer: 5, feedback: 'All five are possible. You can start with a chat, then choose the kind of help or result you need.' },
    ],
  },
  {
    ...base, title: 'From Conversation to Outcome', duration: '4 min',
    summary: 'When you open Replit’s home screen, you’ll see a large composer, also called the prompt box.',
    openingImage: { src: '/images/replit-home-anonymized.png', alt: 'Replit home screen with the large prompt box below the greeting. Names, avatars, and project titles are fictional.' },
    entryLink: 'https://replit.com/~',
    introduction: ['It’s one of the main ways you interact with Replit. Everything starts with a chat where you explain what you want to achieve.', 'In this lesson, you’ll brainstorm birthday-party themes, choose one, and ask for a picture. Keep the same chat open so you can build on your ideas.', 'Use fictional details for this exercise. You don’t need to share a child’s name, photo, or exact location.'],
    promptGate: true,
    outcomes: ['Write a prompt to brainstorm party themes', 'Choose a theme with a follow-up', 'Ask for an image to visualize your idea'],
    sections: [
      { heading: 'Tell Replit what you have in mind', body: 'Write your request in the prompt box. That request is a prompt. Start with the goal and a few helpful details. You’re just asking for ideas for now. You’ll ask for the website later.', prompt: 'I’m planning a birthday party for a six-year-old, with ten children in a park. Help me brainstorm four themes with simple activities.', afterPrompt: 'Send the prompt in Replit and read the suggestions. Notice how your details give the ideas a direction. The answer may differ from someone else’s, and that’s fine.' },
      { heading: 'Let’s choose a theme together', body: 'Read Replit’s suggestions and pick a theme you like. Reply in the same chat so you can build on those ideas. Replace the bracketed text with your choice.', prompt: 'Let’s go with [your chosen theme]. Suggest three simple activities that fit it.', afterPrompt: 'Read the activities and ask for a simpler option if you need one. You can keep the theme while refining the details.' },
      { heading: 'Picture the party', body: 'Now ask for a picture of the theme you chose. You don’t need to repeat the whole plan in the same chat.', prompt: 'Create an image of what this birthday party could look like, with decorations and a picnic table in a park, using our chosen theme.', afterPrompt: 'Look at the picture. Does it fit your idea? You can ask for one change, such as different colors or simpler decorations. That’s a chat: describe, review, and refine.' },
    ],
    quiz: [
      { prompt: 'What does the generated party image show?', choices: ['Proof that every decoration is in stock', 'A visual idea to review and refine', 'A confirmed order from a store'], answer: 1 },
      { prompt: 'How do you refine a theme you like?', choices: ['Accept everything without reviewing it', 'Publish a website first', 'Ask a follow-up in the same chat'], answer: 2 },
      { prompt: 'What helps Replit suggest relevant ideas?', choices: ['Your goal and helpful details', 'Leaving out what you want', 'Using technical vocabulary instead of a goal'], answer: 0 },
    ],
  },
  {
    ...base, title: 'Connect your tools',
    activityConfirmation: 'I have successfully connected my calendar to Replit.',
    summary: 'Connect Google Calendar to Replit so it can help with your schedule. In this lesson, you’ll use the Integrations page, sign in with Google, and review the calendar access you’re granting. You don’t need to connect Gmail or create an event yet.',
    outcomes: ['Find Google Calendar in the Integrations page', 'Sign in with the intended Google account', 'Review calendar permissions before allowing access'],
    sections: [
      { heading: 'Connect to Google Calendar', body: 'Follow these five steps in Replit and Google. The screenshots have account details and private sidebar content removed. Your screen may look slightly different, especially if you already have a connection.' },
      { heading: '1. Locate and open Integrations', body: 'On Replit’s home screen, find Integrations in the left sidebar and click it. This opens the integration library shown below.', image: { src: '/images/calendar-setup/calendar-step-1.webp', alt: 'Replit integration library with Integrations selected in the left sidebar. Account details and private sidebar content are removed.', caption: 'Step 1: Open Integrations from the left sidebar.', source: '/images/calendar-setup/calendar-step-1.webp' } },
      { heading: '2. Search for Calendar', body: 'In the search box at the top of the integration library, type Calendar. Select the Google Calendar card. This screenshot shows an existing connection as Active and Enabled; if yours is already connected, check that it uses the intended account rather than connecting it again.', image: { src: '/images/calendar-setup/calendar-step-2.webp', alt: 'Integration library search results for calendar, including the Google Calendar card.', caption: 'Step 2: Search for Calendar and select Google Calendar.', source: '/images/calendar-setup/calendar-step-2.webp' } },
      { heading: '3. Click Sign in', body: 'On the Google Calendar integration page, click Sign in in the upper-right corner. This begins the connection flow.', image: { src: '/images/calendar-setup/calendar-step-3.webp', alt: 'Google Calendar integration details with a Sign in button in the upper-right corner.', caption: 'Step 3: Start connecting Google Calendar with Sign in.', source: '/images/calendar-setup/calendar-step-3.webp' } },
      { heading: '4. Continue to Google Calendar', body: 'Read the connection dialog, then click Continue to Google Calendar. When Google opens, choose the account whose calendar you want to connect and sign in if prompted. Check the account carefully before continuing.', image: { src: '/images/calendar-setup/calendar-step-4.webp', alt: 'Connect Google Calendar dialog with a Continue to Google Calendar button.', caption: 'Step 4: Continue to Google and choose your account.', source: '/images/calendar-setup/calendar-step-4.webp' } },
      { heading: '5. Review and allow calendar access', body: 'Read the permissions Google displays before clicking Allow. The example includes viewing events and availability, editing events, and broader access to see, edit, share, and permanently delete calendars you can access. These are substantial permissions, not just read-only access. Approve only if you trust Replit with the access shown and are permitted to grant it. Otherwise, cancel. After approval, return to Replit and check that Google Calendar is connected. Connecting does not itself create an event or invite anyone.', image: { src: '/images/calendar-setup/calendar-step-5.webp', alt: 'Google consent screen showing calendar permissions and Cancel and Allow buttons. The browser address is removed.', caption: 'Step 5: Review the actual permissions, then Allow only if you agree.', source: '/images/calendar-setup/calendar-step-5.webp' } },
      { heading: 'Alternatively, ask Replit', body: 'You can also type “Connect to my Google Calendar” in a Replit chat. Replit can guide you through the connection steps. You’ll still choose your Google account and review its permissions yourself. There’s no need to connect Gmail for this lesson.' },
    ],
    quiz: [
      { prompt: 'What does an integration add to this exercise?', choices: ['A guarantee that every answer is right', 'Access to every account automatically', 'Access to an approved source of relevant information'], answer: 2 },
      { prompt: 'What should you check before connecting a tool?', choices: ['The account and the access you are granting', 'Only the color of its icon', 'Whether you have already published an app'], answer: 0 },
      { prompt: 'Does connecting Google Calendar create an event automatically?', choices: ['Yes, it creates a party event immediately', 'No, connecting grants access; creating an event is a separate request', 'Yes, it sends invitations to everyone in your contacts'], answer: 1 },
    ],
  },
  {
    ...base, title: 'Add the birthday to your calendar', duration: '5 min',
    summary: 'Now that Google Calendar is connected, let’s use it. You’ll ask Replit to add a birthday event, review the details, and check the result in Google Calendar. This is a real action in a connected tool, not just a suggested plan.',
    copyPrompts: true,
    activityConfirmation: 'I have successfully added and checked my birthday event in Google Calendar.',
    outcomes: ['Ask Replit to create a calendar event from a prompt', 'Review the details and verify the saved event', 'Understand how integrations let Replit act in connected tools'],
    introduction: [
      'Continue in your party-planning chat with Google Calendar connected. You don’t need Gmail for this activity, including calendar invitations.',
      'The example uses fictional party details: September 22, 2026, from 3:00 to 5:00 PM in the Europe/Zurich time zone. Replace the date, year, time zone, and calendar name with the ones you intend to use. Choose a calendar where you’re allowed to create a test event.',
    ],
    sections: [
      { heading: '1. Ask Replit to add the birthday', body: 'Copy the prompt below, or write it in your own words. Replace [calendar name] before sending it in Replit. Include a title, full date, start and end time, and time zone so Replit doesn’t have to guess. For this first try, don’t add guests or a private address.', prompt: 'Create an event called “Birthday party · practice” on September 22, 2026, from 3:00 to 5:00 PM, using the Europe/Zurich time zone, in my Google Calendar named [calendar name]. Add “Fictional birthday-party planning exercise” to the description. Show me the details before creating it and wait for my confirmation. Ask me if the calendar or any detail is unclear. Don’t add guests or send invitations.', afterPrompt: 'Copying the prompt here does not send it or change your calendar. Paste it into Replit, edit the example details, and send it there.' },
      { heading: '2. Review and confirm', body: 'Read the proposed event. Check the title, date and year, start and end time, time zone, and destination calendar. Correct anything that is wrong in the same chat. Once everything is right, ask Replit to create the event and review any approval card it shows.', prompt: 'Create the one birthday event we just reviewed, using the confirmed details and calendar. Don’t add guests or send invitations. Give me a link to the saved event.' },
      { heading: '3. Check the event in Google Calendar', body: 'Open the returned event link or go to Google Calendar. Check that the event exists on the intended calendar at the correct date and time, and that it has no guests. A proposed event in chat is not the same as a saved event. If creation fails or the result is unclear, check your calendar before trying again so you don’t create duplicates. You can delete the practice event when you’re finished.' },
      { heading: 'Optional: invite your guests', body: 'If you have the email addresses of people you intend to invite, you can ask Replit to add them to the existing event and send Google Calendar invitations. This uses Calendar, not Gmail. Invitations notify real people, so skip this during a fictional practice exercise. For a real party, replace the placeholders, check every address, and review the guest list before authorizing invitations.', prompt: 'For the existing birthday event we just created, prepare to invite [guest email addresses]. Show me the event and guest list first. Don’t add guests or send invitations until I confirm, and don’t create another event.', afterPrompt: 'When the real guest list is correct, explicitly ask Replit to add those guests and send the calendar invitations. Review any approval card, then check the event’s guest list. An invitation is not an RSVP: guests still need to respond.' },
      { heading: 'What did the integration make possible?', body: 'Without an integration, Replit can help write an event title, suggest a schedule, or draft an invitation. Connecting Google Calendar authorizes access to that service within the permissions you granted. Replit can then use Calendar’s tools to create or update an actual event when you ask. Your prompt describes the action; the integration provides access to the calendar; checking the saved event confirms the result.', items: ['Connection: you grant access to a particular Google account and its permitted calendar actions.', 'Request: you tell Replit what to do, with enough detail to avoid guessing.', 'Review: you check the proposed action, especially when it changes data or notifies others.', 'Result: you verify the change in Google Calendar, not just in the chat.'] },
    ],
    quiz: [
      { prompt: 'What does the Google Calendar integration make possible?', choices: ['Creating an actual event in a calendar you authorized', 'Automatically connecting every Google service', 'Inviting people without knowing their email addresses'], answer: 0 },
      { prompt: 'How do you verify that your event was created correctly?', choices: ['Copy the prompt a second time', 'Open the saved event in Google Calendar and check its details', 'Assume a proposed event in chat has already been saved'], answer: 1 },
      { prompt: 'What should you do before asking Replit to send invitations?', choices: ['Create a duplicate event for each guest', 'Connect Gmail even when using Calendar invitations', 'Review the existing event and guest addresses, then explicitly authorize invitations'], answer: 2 },
    ],
  },
  {
    ...base, title: 'Work effectively with Replit',
    activityConfirmation: 'I have searched for items with Replit.',
    summary: 'We’ve brainstormed a party theme, connected our tools, and added the birthday to the calendar. Now let’s create the checklist together. Replit can search the web for supplies and help turn our ideas into a shopping list we can actually use.',
    copyPrompts: true,
    outcomes: ['Search the web for supplies that fit your party theme and budget', 'Check product links, prices, and delivery details', 'Create a checklist you can use to track purchases'],
    sections: [
      { heading: '1. Find supplies for your theme', body: 'Continue in the chat where you chose your theme. Maybe it’s dinosaurs, space, or something entirely different. Let’s find decorations, tableware, and games that fit. Copy this prompt, replace the brackets, and give Replit a budget and a country or region to shop in. There’s no need to share your home address.', prompt: 'Let’s find supplies for the birthday party we’ve been planning. Use our chosen theme, [number] guests, and a shopping budget of [amount and currency]. Search the web for decorations, plates and cups, and simple party-game supplies available in [country or region]. Suggest a few affordable options with product links, quantities, listed prices, and delivery information where available. Ask if the theme or party date is unclear, and flag anything you cannot verify. Don’t buy anything.' },
      { heading: '2. Take a look at what Replit found', body: 'Open a few of the product links. Do the items fit your theme? Are there enough plates for everyone? Check pack sizes, prices, shipping costs, and whether delivery is likely before the party. Prices and availability can change, so treat the results as shopping research, not a reservation. If something isn’t quite right, ask for a small change.', prompt: 'Keep the theme and guest count. Find a less expensive alternative for [item], and update the estimated total. Show the product link and flag any shipping costs or delivery dates you could not confirm.' },
      { heading: '3. Turn your choices into a checklist', body: 'Once you like the options, let’s put everything in one place. Keep the checklist in this chat so you can return to it as you prepare. We’ll use the same list in the next lesson to check your progress each week.', prompt: 'Turn the party supplies we chose into a checklist in this chat. Give each item an ID, quantity, product link, estimated cost, buy-by date, purchase status, and notes. Use “Not started,” “Ordered,” and “Delivered” for purchases, and don’t mark anything bought unless I’ve confirmed it. Add a separate preparation section for invitations and RSVPs, the cake, and planning games. Keep the total within our agreed budget, and show unknown costs separately. Ask about missing details rather than guessing. Don’t place orders or send invitations.', afterPrompt: 'Already have the plates at home? Bought decorations in a shop? Tell Replit and ask it to update the notes. Your updates matter just as much as an email receipt.' },
    ],
    quiz: [
      { prompt: 'What helps Replit find useful party supplies?', choices: ['Your theme, guest count, budget, and shopping region', 'Only the word “shop”', 'Your email password'], answer: 0 },
      { prompt: 'Replit found a product you like. What should you do next?', choices: ['Assume its price and delivery are guaranteed', 'Open the link and check the quantity, price, and delivery details', 'Mark it as delivered'], answer: 1 },
      { prompt: 'Why keep the checklist in your planning chat?', choices: ['It automatically purchases everything', 'It replaces checking the product links', 'You can update it and use it for the weekly progress review'], answer: 2 },
    ],
  },
  {
    ...base, title: 'Create a Routine', duration: '7 min',
    summary: 'Our checklist is ready, and the party is getting closer. Let’s make it easier to keep track of what’s been bought and who’s coming. We’ll connect Gmail, then ask Replit to check for RSVP replies and purchase confirmations each week. That regular check-in is a Routine.',
    copyPrompts: true,
    outcomes: ['Use your existing checklist to track party preparations', 'Connect Gmail to look for RSVP replies and purchase confirmations', 'Set up and review a weekly Routine'],
    sections: [
      { heading: '1. Pick up where we left off', body: 'Open the planning chat and find the checklist you made in the previous lesson. Maybe you’ve ordered the decorations already, or picked up the cups on your way home. Add those updates first. We’re going to review this list, not create a new one each week.', afterPrompt: 'Keep your manual updates in this chat. Replit can look for receipts, but it won’t know about the supplies sitting in your cupboard unless you tell it.' },
      { heading: '2. Let’s connect Gmail', body: 'We connected Google Calendar earlier. Now let’s add Gmail so Replit can find party replies and order confirmations. Open Integrations, search for Gmail, and follow the sign-in steps. Choose the right account and review the permissions before approving. You can also simply ask Replit to connect Gmail.', afterPrompt: 'Finish connecting before scheduling the review, since a Routine can’t sign in for you. Use an account you’re allowed to connect. If you’re just practicing, you can use non-sensitive test messages or review the example without connecting. No purchases or real invitations are required.' },
      { heading: '3. See how preparations are going', body: 'Let’s try a quick check-in. In the chat with your checklist, ask Replit to look for this week’s purchase confirmations in Gmail and update your list.', prompt: 'Check my Gmail for items I purchased this week that are on our birthday checklist. Mark the matching items as ordered and show me the updated checklist with links to the confirmation emails.', afterPrompt: 'Check the matches before moving on. “Ordered” means you’ve bought the item, not that it has arrived. If you bought something in person, tell Replit so it can update that too.' },
      { heading: '4. Make it a weekly check-in', body: 'Happy with the review? Let’s have Replit do this each week. In Replit, we call this creating a Routine. For example, every Monday morning, Replit can check your party emails and give you an update on who’s coming, what you’ve ordered, and what’s still on your checklist. Choose a day, time, and time zone that suit you. If the party is tomorrow, try this with a later practice date so a weekly schedule makes sense.', prompt: 'Let’s make this a weekly Routine called “Birthday preparation check-in,” every Monday at 9:00 AM, Europe/Zurich time. Repeat the Gmail and checklist review we just tried. Include our checklist, party date, email search details, and rules for checking receipts and replies in the instructions. Use the latest checklist and my manual updates in this chat, and tell me if you can’t find them. Each week, post the updated checklist, RSVP summary, purchase updates with email links, anything uncertain, and three suggested next steps here. Don’t send messages, change calendar events, or make purchases. Show me the schedule, instructions, and per-run budget before activating it.', afterPrompt: 'Routines require a paid plan and available workspace access. If you’re not ready to activate one, that’s fine: you can review the proposal and run the check-in manually instead.' },
      { heading: '5. Take a look inside your Routine', body: 'Replit will show you a proposal before the weekly check-in starts. Let’s take a moment to read it together. These details tell Replit what to do, when to do it, and how much it can spend on each run. If something doesn’t match what you had in mind, adjust it before confirming.', items: ['Name: “Birthday preparation check-in” helps you recognize this Routine later.', 'Instructions: review our checklist, look for relevant RSVP emails and purchase confirmations, and report what still needs attention. Check that the checklist items and email search details are included, with no permission to buy anything or send messages.', 'Schedule and time zone: our example is every Monday at 9:00 AM, Europe/Zurich time. Make sure that works for you.', 'Per-run budget: this is the budget for Replit to carry out one check-in, not your party-shopping budget. It applies to each run, not to the entire series of weekly reviews. Review the amount before activating.', 'Expected result: an updated checklist, RSVP summary, purchase updates with email links, and suggested next steps returned to this chat.'] },
      { heading: '6. Turn it on and follow your progress', body: 'Happy with the details? Confirm the proposal when you’re ready to start. Then open Routines in the sidebar to find your check-in and review its schedule and activity. A proposal on its own is not an active Routine. Make sure Gmail access works before the first run; if a run gets stuck needing permission, come back to the chat to resolve it.', items: ['Check whether the Routine is enabled and when it is scheduled to run next.', 'After a run, check its activity and come back to this chat for the report and supporting email links.', 'Keep adding your own updates, especially purchases made in person.', 'If an email search fails or is incomplete, check again rather than assuming nothing has changed.', 'After the party, pause or delete the Routine. Recurring runs can use paid capacity.'] },
      { heading: 'A little less checking to do yourself', body: 'You’ve gone from brainstorming a theme to finding supplies, making a checklist, and setting up a regular progress update. Gmail gives Replit the information to check; the Routine makes that check happen on a schedule. You still decide what to buy and who to contact. Replit helps you see what’s ready and what needs your attention next.' },
    ],
    practice: { prompt: 'Give me a quick recap of our birthday check-in: which checklist and emails it will review, when it will run, the time zone and budget, and where I can read the results. Remind me how to turn it off after the party. Don’t activate it or change any settings in this recap.', checks: ['I found my checklist from the previous lesson and added any progress updates.', 'I tried the Gmail review, or reviewed the example without connecting an account.', 'I checked the weekly schedule, time zone, and budget before deciding whether to activate it.', 'I know where to read my updates and how to turn the Routine off after the party.'] },
    quiz: [
      { prompt: 'Which task is this Routine repeating?', choices: ['Buying every unfinished checklist item', 'Reviewing relevant RSVP emails and purchase evidence against the checklist each week', 'Sending invitations to everyone in your inbox'], answer: 1 },
      { prompt: 'A receipt confirms that decorations were ordered. What does that establish?', choices: ['The decorations have arrived', 'Every party preparation task is complete', 'The decorations were ordered; delivery still needs separate evidence'], answer: 2 },
      { prompt: 'No matching email was found for a checklist item. What should the report say?', choices: ['No email evidence found; check for manual or offline updates', 'The task definitely has not been done', 'The guest declined the invitation'], answer: 0 },
      { prompt: 'What should you review before activating one?', choices: ['Only its title', 'Only the first sentence of the request', 'Its task, schedule, time zone, and per-run budget'], answer: 2 },
      { prompt: 'What is the Routine’s per-run budget for?', choices: ['Buying the supplies on your party checklist', 'Replit carrying out one scheduled check-in', 'All weekly check-ins combined, forever'], answer: 1 },
      { prompt: 'Where do you review a Routine’s results?', choices: ['In the chat it belongs to', 'Only inside an app’s code files', 'They are never available after a run'], answer: 0 },
    ],
  },
  {
    ...base, title: 'Build and Publish a Simple App', duration: '6 min',
    summary: 'Your chat has helped you make a plan. Now you can turn part of that plan into something you can use: a small app for organizing gathering activities.',
    outcomes: ['Describe one manageable first version', 'Try the app in Preview', 'Request and test one improvement'],
    sections: [
      { heading: 'Choose one thing the app should do', body: 'Start with an activity list. You should be able to add an idea and mark it as chosen. Leave invitations, accounts, and payments for later. A smaller first version gives you something concrete to try sooner.' },
      { heading: 'Ask Replit to build it', body: 'Open a new chat or continue your planning chat. Say explicitly that you want a web app. Replit creates a project for the work and writes the files that make the app function. Building can take a few minutes; keep the chat open and respond if it needs clarification.' },
      { heading: 'Try the first version', body: 'When the app is available, open Preview. Add an activity, mark it as chosen, and check that the list changes. A message saying the app is ready is your cue to test, not proof that every detail is right.' },
      { heading: 'Make one improvement', body: 'Ask for an improvement you can see and test. Keep the existing functionality so you can tell whether the change helped.', prompt: 'Keep adding activities and marking them as chosen. Add a filter that shows only chosen activities. Don’t add accounts or publish the app.', afterPrompt: 'Try the filter with both chosen and unchosen activities. If it doesn’t work as expected, describe what you did, what happened, and what you wanted instead.' },
      { heading: 'Sharing is a separate decision', body: 'You don’t need to publish to finish this lesson. Before sharing, review access and remove private information. A development preview is not the same as a finished release, and you should not assume its link is private. The Build course goes deeper into the app’s parts, testing, and publishing.' },
    ],
    practice: { prompt: 'Build a simple web app for planning a neighborhood gathering. Let me add an activity and mark it as chosen. Use sample information and store the list only in this browser. No accounts, invitations, or payments. Don’t publish it.', checks: ['I opened the app in Preview and tried adding and choosing an activity.', 'I requested one improvement and tested the changed behavior.'] },
    quiz: [
      { prompt: 'What belongs in a manageable first version?', choices: ['Every future feature', 'Payments and accounts before anything else', 'One useful activity-list workflow you can test'], answer: 2 },
      { prompt: 'Replit says the app is ready. What comes next?', choices: ['Try its main actions in Preview', 'Assume every feature works', 'Share private information in it immediately'], answer: 0 },
      { prompt: 'Do you have to publish to finish this exercise?', choices: ['Yes, testing only works after publishing', 'No, try and improve the app before deciding to share it', 'Yes, every chat publishes automatically'], answer: 1 },
    ],
  },
  {
    ...base, title: 'Create a Design and Image',
    summary: 'Your app can work and still not feel quite how you imagined. Design helps you explore how it looks and how people find their way around it.',
    outcomes: ['Describe a visual direction in everyday language', 'Review a design against its purpose', 'Create an image and refine one detail'],
    sections: [
      { heading: 'Describe a feeling and a purpose', body: 'For your gathering, you might want a friendly, welcoming page with clear activity cards. You can describe colors, spacing, and the mood without knowing design terminology. Say who will use it and which action should be easy to find.' },
      { heading: 'Explore before changing the app', body: 'Ask Replit for a design direction. Make it clear whether you want to explore an idea or apply it to your existing app. Compare readability, the main action, and how the page fits your audience. Looking good is only part of a useful design.' },
      { heading: 'Create a supporting image', body: 'An image can make the idea feel more real. Describe its subject, style, and where it will appear. Use an original illustration rather than copying a brand or someone else’s artwork.', prompt: 'Create an original, warm illustration of neighbors gathering around a shared table. Use a simple style and soft colors, with no text or logos. It will be a wide header image for a gathering planner.', afterPrompt: 'Inspect the result. Does it fit the page? Is there room for the heading? Ask for one change, such as a quieter background, and compare the versions.' },
      { heading: 'Keep exploring at your own pace', body: 'You’ve moved from a question to useful context, a plan, a recurring-task proposal, an app, and a visual direction. These are options you can combine, not a checklist for every project. Choose the next step that helps your idea. More in-depth lessons are coming soon.' },
    ],
    practice: { prompt: 'Explore a design for my neighborhood gathering planner. Make it warm and welcoming, with readable activity cards and an obvious Add activity button. Show a first direction without changing or publishing my existing app.', checks: ['I reviewed a design for readability and its main action.', 'I requested an original image and reviewed one refinement.'] },
    quiz: [
      { prompt: 'What makes a useful design request?', choices: ['The audience, purpose, and visual direction you want', 'Only “make it better”', 'A requirement to use technical design terms'], answer: 0 },
      { prompt: 'What should you check besides appearance?', choices: ['How many colors are available', 'Whether people can read the content and find the main action', 'Whether every element is animated'], answer: 1 },
      { prompt: 'What is a useful next step after the first image?', choices: ['Accept it without looking', 'Change the whole project automatically', 'Review it in context and request one specific refinement'], answer: 2 },
    ],
  },
];
